### ISSUE TITLE
where is the paper?

### ISSUE THREAD

**Issue by zyl1336110861** [decadenza/DirectStereoRectification#1]
@decadenza Hi, thank you very much for sharing your code! When I want to read your paper, I failed to find it. So can you show me where I can get it?

**Comment by decadenza** [comment]
Hi @zyl1336110861 and thanks for your interest.

The paper is undergoing the peer review process.
I should have been more clear in the readme.
I will put the pdf as soon as it is published.

In practice it offers a closed-form solution of the minimum perspective distortion, starting from the problem definition of Loop and Zhang.

Hopefully it will be published soon.

Regards

**Comment by zyl1336110861** [comment]
@decadenza Ok! Can you tell me which journal you have submitted to? Maybe I will cite your work.

**Comment by decadenza** [comment]
Thanks! I am waiting for final approval and then I'll disclose all the info.

**Comment by decadenza** [comment]
Journal will be "Lecture Notes in Networks and Systems" https://www.springer.com/series/15179.
I'll update in readme.

**Comment by decadenza** [comment]
Hi @zyl1336110861 
I just wanted to share with you the pre-print version of the paper. You can find it here: https://arxiv.org/abs/2203.00123

Official publication will be in Lecture Notes in Networks and Systems in July 2022.

Cheers
