### ISSUE TITLE
stereo rectification between pinhole and fisheye

### ISSUE THREAD

**Issue by williamhyin** [decadenza/DirectStereoRectification#4]
Hi 

Thanks for your great work. And  I'm looking forward to your paper.

I have a question about the stereo rectification between pinhole and fisheye.
Is there possible to use your algorithms to realize stereo rectification between pinhole and fisheye?

If possible ,how could i modify your code？

Thanks

**Comment by decadenza** [comment]
Hi @williamhyin and thank you.

This works for the classic pinhole camera model. As far as I know, the fisheye camera model is different and I am not sure that the same procedure can be applied to it.

You may want to start from [the fisheye basics](https://www.mathworks.com/help/vision/ug/fisheye-calibration-basics.html) (and maybe compare with [classic pinhole basics](https://uk.mathworks.com/help/vision/ug/camera-calibration.html)) and then have a look at the dedicated  [OpenCV fisheye rectification](https://docs.opencv.org/4.x/db/d58/group__calib3d__fisheye.html#gac1af58774006689056b0f2ef1db55ecc).

I am closing this enhancement request as it is not in the plans now, but please share your findings with us! There may be a way to apply the same reasoning to fisheye...
