### ISSUE TITLE
Uncalibrated rectification

### ISSUE THREAD

**Issue by Tord-Zhang** [decadenza/DirectStereoRectification#8]
Hi, If I get two images not perfectly rectified, i.e., there are negative disparities, is it possible to rectify there two images with this code?

**Comment by decadenza** [comment]
If you have the original images and the calibration parameters, yes.
Since your title is "uncalibrated rectification" I suspect you don't have these. Could you share something more?

**Comment by Tord-Zhang** [comment]
> If you have the original images and the calibration parameters, yes. Since your title is "uncalibrated rectification" I suspect you don't have these. Could you share something more?

Thanks for your response! By "uncalibrated rectification", I mean that I got two images captured by camera  with unknown intrinsics. And also I do not know the distance these two camera. It is possible to rectify?

**Comment by decadenza** [comment]
Unfortunately not, this code starts from known calibration intrinsic and extrinsic parameters. If possible, is always better to calibrate to improve the quality of the final 3D reconstruction.
I suggest to search for the appropriate algorithm (maybe you may start from scholar.google.com). There are plenty that are able to estimate the parameters.

Good luck.
